### ISSUE TITLE
Unable to import via gradle

### ISSUE THREAD

**Issue by larrytech7** [freecats/TextViewExpandableAnimation#4]
I wan to import via gradle and i use

`com.github.freecats:TextViewExpandableAnimation:9ceeecacac`

but it shows me error unable to resolve library. I think it needs a version at the end than the 9ceee... stuff there. What version of the library are we to import?

**Comment by freecats** [comment]
Sorry，but this library  didn't upload to Maven Repository or JCenter，so it didn't have a version number. As the README.MD says，you need to clone or download library and copy the code into your project and then you should ready to go.

**Comment by DrashtiKapadia** [comment]
where is the library file ?

**Comment by DrashtiKapadia** [comment]
do i have to post whole project in my project how to do that i am stuck since 2 days please revert soon

**Comment by DrashtiKapadia** [comment]
it is showing ::: android.view.InflateException: Binary XML file line #22: Error inflating class com.freecats.demo.view.TextViewExpandableAnimation

please help

**Comment by DrashtiKapadia** [comment]
i dont think without dependencies it will work

**Comment by DrashtiKapadia** [comment]
its done thanks anyways nicely implementated
